---
# 🟢 PARTIE EXTRACT

### Ex E1 ⭐ — Explorer les sources
Affichez pour chaque DataFrame : shape, colonnes, dtypes, et les 3 premières lignes.

In [10]:
import pandas as pd

In [5]:
clients = pd.read_csv("data/clients.csv")
commandes_Q1 = pd.read_csv("data/commandes_Q1.csv")
commandes_Q2 = pd.read_csv("data/commandes_Q2.csv")
produits = pd.read_csv("data/produits.csv")

In [3]:
clients.shape

(515, 9)

In [5]:
clients.columns

Index(['client_id', 'nom', 'email', 'ville', 'region', 'segment',
       'date_inscription', 'ca_historique', 'actif'],
      dtype='str')

In [6]:
clients.head(3)

,client_id,nom,email,ville,region,segment,date_inscription,ca_historique,actif
0,CLI0001,Client_1,client1@email.fr,Toulouse,Auvergne-RA,Startup,2021-02-01,129.67,True
1,CLI0002,Client_2,client2@email.fr,Lyon,Nouvelle-Aquitaine,Particulier,2022-08-11,42431.54,False
2,CLI0003,Client_3,client3@email.fr,Nantes,Occitanie,PME,2023-11-17,6895.77,True

In [8]:
commandes_Q1.shape

(3020, 10)

In [9]:
commandes_Q1.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison'],
      dtype='str')

In [10]:
commandes_Q1.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine

In [12]:
commandes_Q2.shape

(3220, 11)

In [13]:
commandes_Q2.head(3)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,moyen_paiement,region_livraison,devise
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR

In [4]:
produits.shape

(152, 7)

In [9]:
produits.head(3)

,produit_id,nom,categorie,prix_unitaire,stock,fournisseur,actif
0,PRD0001,Produit_Inf_1,Informatique,57.96,71,TechPro,True
1,PRD0002,Produit_Inf_2,Informatique,135.96,102,MediaShop,True
2,PRD0003,Produit_Inf_3,Informatique,83.45,372,ElecPlus,False

### Ex E2 ⭐ — Détecter les différences entre Q1 et Q2
Trouvez les colonnes présentes dans Q2 mais absentes de Q1, et vice-versa.
Affichez les différences clairement.

In [ ]:
Dans commandes_Q2, on a la colonne devise en plus, mode_paiement en Q1 devient moyen_paiement en Q2

### Ex E3 ⭐ — Harmoniser les colonnes
1. Renommez la colonne problématique dans Q2 pour qu'elle corresponde à Q1
2. Ajoutez la colonne manquante dans Q1 avec une valeur par défaut
3. Vérifiez que les deux DataFrames ont maintenant les mêmes colonnes

In [10]:
commandes_Q2.rename(columns={"moyen_paiement":"mode_paiement"},inplace=True)
commandes_Q2.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise'],
      dtype='str')

In [11]:
commandes_Q1["devise"] = "EUR"

In [15]:
commandes_Q1.head()

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024

In [16]:
commandes_Q2.head()

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q2-00001,CLI0122,PRD0041,5,48.15,240.75,2024-05-14,retournée,CB,Auvergne-RA,EUR,Q2_2024
1,CMD-Q2-00002,CLI0346,PRD0106,1,52.42,52.42,2024-04-18,livrée,CB,PACA,EUR,Q2_2024
2,CMD-Q2-00003,CLI0282,PRD0021,8,78.18,625.44,2024-05-05,annulée,CB,Occitanie,EUR,Q2_2024
3,CMD-Q2-00004,CLI0292,PRD0141,9,326.57,2939.13,2024-05-31,livrée,Chèque,Occitanie,EUR,Q2_2024
4,CMD-Q2-00005,CLI0392,PRD0054,5,124.37,621.85,2024-06-27,livrée,CB,Auvergne-RA,EUR,Q2_2024

### Ex E4 ⭐ — Consolider avec pd.concat
1. Ajoutez une colonne `source` dans Q1 (`'Q1_2024'`) et Q2 (`'Q2_2024'`)
2. Concaténez Q1 et Q2 avec `pd.concat`
3. Vérifiez que le total de lignes est cohérent
4. Affichez la répartition des lignes par source

In [14]:
commandes_Q1["source"] = "Q1_2024"
commandes_Q2["source"] = "Q2_2024"

In [17]:
commandes_Q12 = pd.concat([commandes_Q1, commandes_Q2])

In [29]:
commandes_Q12.value_counts("source")

source
Q2_2024    3220
Q1_2024    3020
Name: count, dtype: int64

### Ex E5 ⭐⭐ — Fonction extract()
Encapsulez tout dans une fonction `extract(q1_path, q2_path, clients_path, produits_path) -> dict`
qui retourne un dictionnaire avec les 4 DataFrames harmonisés et consolidés.
La fonction doit afficher des logs à chaque étape.

In [11]:
import logging

logging.basicConfig(level=logging.INFO, format="%(asctime)s | %(message)s", datefmt="%H:%M:%S")
logger = logging.getLogger("ETL")

def extract(q1_path, q2_path, clients_path, produits_path):
    res = {}
    try:
        for path in [q1_path, q2_path, clients_path, produits_path]:
            res[path] = pd.read_csv(path)
            logger.info("chargement de "+path+" réussi")
    except:
        logger.error("chargement de "+path+" a échoué")
        raise
    try:
        res[q2_path].rename(columns={"moyen_paiement":"mode_paiement"},inplace=True)
        logger.info("renommage de la colonne moyen_paiement de Q2 réussi")
    except:
        logger.error("renommage de la colonne moyen_paiement de Q2 a échoué")
        raise
    try:
        res[q1_path]["devise"] = "EUR"
        logger.info("ajout de la colonne devise dans Q1 réussi")
    except:
        logger.error("ajout de la colonne devise dans Q1 a échoué")
        raise
    try:
        res[q1_path]["source"] = "Q1_2024"
        res[q2_path]["source"] = "Q2_2024"
        logger.info("ajout de la colonne source dans Q1 et Q2 réussi")
    except:
        logger.error("ajout de la colonne source dans Q1 et Q2 a échoué")
        raise
    try:
        commandes_q1q2 = pd.concat([res[q1_path], res[q2_path]],ignore_index=True)
        logger.info("concaténation de Q1 et Q2 réussie")
    except:
        logger.error("concaténation de Q1 et Q2 a échoué")
        raise
    return (commandes_q1q2,res[clients_path],res[produits_path])
data = extract("data/commandes_Q1.csv","data/commandes_Q2.csv","data/clients.csv","data/produits.csv")

14:32:32 | chargement de data/commandes_Q1.csv réussi
14:32:32 | chargement de data/commandes_Q2.csv réussi
14:32:33 | chargement de data/clients.csv réussi
14:32:33 | chargement de data/produits.csv réussi

INFO : renommage de la colonne moyen_paiement de Q2 réussi
INFO : ajout de la colonne devise dans Q1 réussi
INFO : ajout de la colonne source dans Q1 et Q2 réussi
INFO : concaténation de Q1 et Q2 réussie

In [80]:
data[0]

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024
...,...,...,...,...,...,...,...,...,...,...,...,...
6235,CMD-Q2-00605,CLI0341,PRD0095,8,106.83,854.64,2024-05-02,retournée,CB,Île-de-France,EUR,Q2_2024
6236,CMD-Q2-02643,CLI0493,PRD0076,9,211.08,1899.72,2024-06-19,en_cours,CB,Occitanie,EUR,Q2_2024
6237,CMD-Q2-00511,CLI0428,PRD0081,6,49.36,296.16,2024-04-05,livrée,CB,Occitanie,EUR,Q2_2024
6238,CMD-Q2-02836,CLI0085,PRD0126,1,82.76,82.76,2024-05-14,livrée,CB,Occitanie,EUR,Q2_2024
6239,CMD-Q2-03170,CLI0122,PRD0120,5,107.93,539.65,2024-04-02,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q2_2024

---
# 🟡 PARTIE TRANSFORM

### Ex T1 ⭐ — Audit initial
Écris une fonction `audit_dataframe(df, nom)` qui affiche :
- Shape
- Nombre de NaN total et par colonne (en %)
- Nombre de doublons
- Types de chaque colonne

In [84]:
def audit_dataframe(df):
    print("Nombre de lignes :",df.shape[0],", nombre de colonnes :",df.shape[1])
    nbtotnull = df.isnull().sum().sum()
    print("Nombre total de Nan :",nbtotnull)
    if nbtotnull > 0:
        dfnul = df.isnull().sum()/nbtotnull*100
        print("Nombre Nan par colonne (%) :")
        print(dfnul)
    print("\nType des colonnes :")
    print(df.dtypes)
audit_dataframe(data[0])

Nombre de lignes : 6149 , nombre de colonnes : 21
Nombre total de Nan : 120
Nombre Nan par colonne (%) :
commande_id                     0.0
client_id                       0.0
produit_id                      0.0
quantite                        0.0
prix_unitaire                   0.0
montant_total                   0.0
date_commande                   0.0
statut                          0.0
mode_paiement                   0.0
region_livraison                0.0
devise                          0.0
source                          0.0
mois                            0.0
annee                           0.0
trimestre                       0.0
jour_semaine                    0.0
tranche_montant                 0.0
saison                          0.0
est_annulee                     0.0
ca_perdu                        0.0
delai_inscription_commande    100.0
dtype: float64

Type des colonnes :
commande_id                               str
client_id                                 str
produit_id                                str
quantite                                int64
prix_unitaire                         float64
montant_total                         float64
date_commande                  datetime64[us]
statut                                    str
mode_paiement                             str
region_livraison                          str
devise                                    str
source                                    str
mois                                    int64
annee                                   int64
trimestre                               int64
jour_semaine                            int64
tranche_montant                      category
saison                               category
est_annulee                              bool
ca_perdu                              float64
delai_inscription_commande    timedelta64[us]
dtype: object

### Ex T2 ⭐ — Supprimer les doublons
Sur le DataFrame consolidé :
1. Détectez et affichez le nombre de doublons
2. Montrez 3 exemples de lignes dupliquées
3. Supprimez les doublons (gardez la première occurrence)
4. Vérifiez qu'il n'en reste plus

In [28]:
cmddbl = data[2].value_counts("produit_id")>1
nbdbl = 0
for index in cmddbl.keys():
    if cmddbl[index]:
        print(index)
        nbdbl += 1
print("Au total,",nbdbl,"doublons")

Au total, 0 doublons

In [12]:
def delete_doublon(df,key):
    cmddbl = df.value_counts(key)>1
    for index in cmddbl.keys():
        if cmddbl[index]:
            print(df[df[key]==index].index.max(),index)
            df.drop(df[df[key]==index].index.max(),inplace=True)
delete_doublon(data[0],"commande_id")
delete_doublon(data[1],"client_id")
delete_doublon(data[2],"produit_id")

3009 CMD-Q1-00014
3001 CMD-Q1-00072
3002 CMD-Q1-00145
3012 CMD-Q1-00345
3013 CMD-Q1-00715
3008 CMD-Q1-00732
3005 CMD-Q1-00986
3011 CMD-Q1-00998
3003 CMD-Q1-01099
3017 CMD-Q1-01222
3007 CMD-Q1-01301
3019 CMD-Q1-01522
3004 CMD-Q1-01526
3006 CMD-Q1-01567
3016 CMD-Q1-01687
3018 CMD-Q1-02488
3015 CMD-Q1-02619
3014 CMD-Q1-02845
3010 CMD-Q1-02926
3000 CMD-Q1-02950
6221 CMD-Q2-00284
6220 CMD-Q2-00366
6237 CMD-Q2-00511
6234 CMD-Q2-00536
6235 CMD-Q2-00605
6223 CMD-Q2-00714
6231 CMD-Q2-00892
6225 CMD-Q2-00944
6232 CMD-Q2-01191
6230 CMD-Q2-01344
6224 CMD-Q2-01898
6233 CMD-Q2-01903
6222 CMD-Q2-02366
6226 CMD-Q2-02403
6236 CMD-Q2-02643
6238 CMD-Q2-02836
6229 CMD-Q2-02943
6227 CMD-Q2-03030
6228 CMD-Q2-03143
6239 CMD-Q2-03170
501 CLI0014
513 CLI0033
505 CLI0041
509 CLI0092
514 CLI0163
508 CLI0170
510 CLI0173
512 CLI0198
504 CLI0199
511 CLI0248
502 CLI0341
503 CLI0367
500 CLI0392
506 CLI0437
507 CLI0498

### Ex T3 ⭐ — Corriger les types
1. Convertissez `date_commande` en datetime en gérant les formats incohérents
2. Extrayez : `annee`, `mois`, `trimestre`, `jour_semaine`
3. Convertissez `quantite` en numérique avec gestion des erreurs
4. Affichez les types avant et après

In [13]:
date_commande = pd.to_datetime(data[0]["date_commande"], errors='coerce')

In [14]:
listeNaT = date_commande.isna()

In [15]:
for index in listeNaT.keys():
    if listeNaT[index]:
        date_commande[index] = pd.to_datetime(data[0]["date_commande"].loc[index],format="%Y/%m/%d")

In [16]:
data[0]["date_commande"] = date_commande

In [15]:
dc = data[0]["date_commande"].loc[4]
print(dc.year,dc.month,dc.quarter,dc.weekday())

2024 3 1 2

In [17]:
data[0]["mois"] = data[0]["date_commande"].apply(lambda col: col.month)

In [18]:
data[0]["annee"] = data[0]["date_commande"].apply(lambda col: col.year)

In [19]:
data[0]["trimestre"] = data[0]["date_commande"].apply(lambda col: col.quarter)

In [20]:
data[0]["jour_semaine"] = data[0]["date_commande"].apply(lambda col: col.weekday())

In [ ]:
df["date_commande"] = pd.to_datetime(df["date_commande"],errors="coerce")
df["annee"] = df["date_commande"].dt.year

### Ex T4 ⭐⭐ — Traiter les NaN
Pour chaque colonne avec des NaN, choisissez et appliquez la stratégie adaptée :
- `montant_total` NaN → recalculer depuis `quantite × prix_unitaire`
- `statut` NaN → valeur par défaut `'inconnu'`
- `date_commande` NaT → supprimer la ligne (donnée critique)

Justifiez chaque choix dans un commentaire.

In [21]:
listeMtNaN = data[0]["montant_total"].isna()
for index in listeMtNaN.keys():
    if listeMtNaN[index]:
        data[0].loc[index,"montant_total"] = data[0]["quantite"].loc[index] * data[0]["prix_unitaire"].loc[index]

In [22]:
listeMtNaN = data[0]["montant_total"].isna()
for index in listeMtNaN.keys():
    if listeMtNaN[index]:
        print(index)

In [23]:
listeSttNaN = data[0]["statut"].isna()
for index in listeSttNaN.keys():
    if listeSttNaN[index]:
        print(index)
        data[0].loc[index,"statut"] = "inconnu"

63
181
273
398
411
506
751
956
1195
1323
1401
1442
1464
1579
1654
1661
1670
1816
2015
2093
2205
2370
2408
2423
2452
2691
2729
2825
2887
2889
2997
3071
3306
3372
3451
3485
3773
4020
4060
4122
4211
4262
4265
4284
4300
4314
4495
4503
4775
4813
4894
5228
5232
5238
5675
5752
5773
5947
6000
6022
6063
6206

### Ex T5 ⭐⭐ — Détecter et traiter les aberrants
1. Détectez les prix négatifs → supprimez ces lignes
2. Détectez les quantités nulles ou négatives → supprimez
3. Vérifiez la cohérence `montant_total = quantite × prix_unitaire` → corrigez les incohérences
4. Affichez un résumé des corrections effectuées

In [24]:
rows = data[0][data[0]["prix_unitaire"]<0].index
data[0].drop(rows,inplace=True)

In [25]:
rows = data[0][data[0]["quantite"]<=0].index
data[0].drop(rows,inplace=True)

In [26]:
rows = data[0][data[0]["quantite"]*data[0]["prix_unitaire"]!=data[0]["montant_total"]].index
for index in rows:
    data[0].loc[index,"montant_total"] = data[0]["quantite"].loc[index] * data[0]["prix_unitaire"].loc[index]

In [27]:
rows = data[0][data[0]["quantite"]*data[0]["prix_unitaire"]!=data[0]["montant_total"]].index
rows

Index([], dtype='int64')

### Ex T6 ⭐⭐ — Jointures avec les référentiels
1. Nettoyez `df_clients` (doublons sur `client_id`)
2. Filtrez `df_produits` pour ne garder que les produits actifs
3. Faites un LEFT JOIN commandes ← clients (colonnes : ville, region, segment)
4. Faites un LEFT JOIN commandes ← produits (colonnes : nom, categorie, fournisseur)
5. Vérifiez le nombre de lignes avant et après (doit être identique avec LEFT JOIN)

In [28]:
delete_doublon(data[1],"client_id")

In [ ]:
# 1 déjà fait par le traitement des doublons en T2
# 2 : pas d'accord : une commande a pu être passée avant qu'un produit devienne inactif

In [29]:
delete_doublon(data[0],"commande_id")

In [44]:
res = data[0].merge(data[1][["client_id","ville","region","segment"]],on="client_id",how="left")

In [45]:
res = res.merge(data[2][["produit_id","nom","categorie","fournisseur"]],on="produit_id",how="left")

In [46]:
print(len(data[0]),len(res))

6149 6149

### Ex T7 ⭐⭐ — Feature Engineering
Créez les colonnes suivantes :
1. `tranche_montant` : `<100€` / `100-500€` / `500-2000€` / `>2000€` avec `pd.cut()`
2. `saison` : depuis le mois (Hiver/Printemps/Été/Automne)
3. `est_annulee` : booléen True si statut == 'annulée'
4. `ca_perdu` : montant_total si commande annulée, sinon 0
5. `delai_inscription_commande` : nb de jours entre date_inscription du client et date_commande

Affichez `value_counts()` pour les colonnes catégorielles créées.

In [159]:
data[0].head()

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,tranche_montant
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,<100€
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,500-2000€
2,CMD-Q1-00003,CLI0044,PRD0128,7,99.94,699.58,2024-01-15,livrée,PayPal,Nouvelle-Aquitaine,EUR,Q1_2024,500-2000€
3,CMD-Q1-00004,CLI0381,PRD0061,8,75.83,606.64,2024-01-17,annulée,PayPal,PACA,EUR,Q1_2024,500-2000€
4,CMD-Q1-00005,CLI0187,PRD0040,4,71.91,287.64,2024-03-20,en_cours,CB,Occitanie,EUR,Q1_2024,100-500€

In [30]:
data[0]["tranche_montant"] = pd.cut(data[0]["montant_total"],bins=[-10,100,500,2000,10000],labels=["<100€","100-500€","500-2000€",">2000€"])

In [33]:
data[0].head(2)

,commande_id,client_id,produit_id,quantite,prix_unitaire,montant_total,date_commande,statut,mode_paiement,region_livraison,devise,source,mois,annee,trimestre,jour_semaine,tranche_montant
0,CMD-Q1-00001,CLI0496,PRD0081,1,49.36,49.36,2024-03-18,annulée,CB,Occitanie,EUR,Q1_2024,3,2024,1,0,<100€
1,CMD-Q1-00002,CLI0305,PRD0058,5,118.62,593.10,2024-01-23,livrée,CB,Occitanie,EUR,Q1_2024,1,2024,1,1,500-2000€

In [31]:
data[0]["saison"] = pd.cut(data[0]["trimestre"],bins=[0,1.5,2.5,3.5,5],labels=["Hiver","Printemps","Eté","Automne"])

In [32]:
data[0]["est_annulee"] = data[0]["statut"] == "annulée"

In [33]:
data[0]["ca_perdu"] = data[0]["est_annulee"] * data[0]["montant_total"]

In [34]:
res = data[0].merge(data[1][["client_id","date_inscription"]],on="client_id",how="left")

In [35]:
res["date_inscription"] = pd.to_datetime(res["date_inscription"], errors='coerce')

In [36]:
data[0]["delai_inscription_commande"] = res["date_commande"] - res["date_inscription"]

In [37]:
data[1]["date_inscription"][(pd.to_datetime(data[1]["date_inscription"], errors='coerce')).isna()]

Series([], Name: date_inscription, dtype: str)

In [82]:
print(len(data[0].client_id.unique()),len(data[1].client_id.unique()))

543 500

In [83]:
data[0]["delai_inscription_commande"].isnull().sum()

np.int64(120)

### Ex T8 ⭐⭐⭐ — Validation qualité
Écris une fonction `valider_pipeline(df) -> bool` qui :
1. Vérifie qu'il n'y a plus de NaN sur les colonnes critiques
2. Vérifie qu'il n'y a plus de doublons
3. Vérifie que tous les prix sont > 0
4. Vérifie que toutes les quantités sont > 0
5. Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près)
6. Retourne True si tout est OK, False sinon avec les erreurs détaillées

In [38]:
def valider_pipeline(df):
    err = []
    # Vérifie qu'il n'y a plus de NaN sur les colonnes critiques :
    for col in ("commande_id","client_id","produit_id","quantite","prix_unitaire","montant_total","date_commande","statut","mode_paiement"):
        nbnull = df[col].isnull().sum()
        if nbnull > 0:
            err.append("Colonne "+col+" : "+str(nbnull)+" NaN")
    # Vérifie qu'il n'y a plus de doublons :
    listDbl = df.value_counts("commande_id")>1
    for key in listDbl.keys():
        if listDbl[key]:
            err.append("Clé "+key+" en doublon")
    # Vérifie que tous les prix sont > 0 :
    for col in ("prix_unitaire","montant_total"):
        nbPrixNeg = (df[col]<0).sum()
        if nbPrixNeg > 0:
            err.append("Colonne "+col+" : "+str(nbPrixNeg)+" prix négatifs")
    # Vérifie que toutes les quantités sont > 0 :
    nbQuantNeg = (df["quantite"]<=0).sum()
    if nbQuantNeg > 0:
        err.append("Colonne quantite : "+str(nbQuantNeg)+" quantités négatives ou nulles")
    # Vérifie que montant_total == quantite × prix_unitaire (à 1 centime près) :
    for cmd in df.itertuples(index=False):
        if abs(cmd.montant_total - cmd.prix_unitaire * cmd.quantite) > 0.01:
            err.append("Commande "+cmd.commande_id+" : montant_total différent de prix_unitaire * quantite")
    # Retourne True si tout est OK, False sinon avec les erreurs détaillées :
    if len(err) > 0:
        print("Liste des erreurs :")
        for e in err:
            print(e)
        return False
    else:
        return True
valider_pipeline(data[0])

True

In [99]:
for cmd in data[0].itertuples(index=False):
    print(cmd.commande_id)
    break

CMD-Q1-00001

### Ex T9 ⭐⭐⭐ — Analyse métier post-transform
Maintenant que les données sont propres, répondez en code :
1. Quel est le CA total du S1 2024 ?
2. Quel trimestre a le CA le plus élevé ?
3. Quelle région génère le plus de CA ?
4. Quel segment client est le plus rentable ?
5. Quelle catégorie de produit a le taux d'annulation le plus élevé ?
6. Quel est le CA perdu sur les annulations ?

In [104]:
CA_Q1_2024 = data[0]["montant_total"][data[0]["trimestre"]==1].sum()

In [105]:
CA_Q2_2024 = data[0]["montant_total"][data[0]["trimestre"]==2].sum()

In [106]:
CA_S1_2024 = CA_Q1_2024 + CA_Q2_2024

In [107]:
print(CA_S1_2024, CA_Q1_2024, CA_Q2_2024)

4037134.7800000003 1939957.84 2097176.9400000004

In [137]:
res = data[0].merge(data[1][["client_id","segment"]],on="client_id",how="left")

In [145]:
res[["segment","montant_total"]].groupby("segment").sum().sort_values(by="montant_total",ascending=False) # Particulier a le CA le plus haut

              montant_total
segment
Particulier      2128659.35
PME              1034674.56
Grand Compte      442118.58
Startup           397170.60

In [39]:
res = data[0].merge(data[2][["produit_id","categorie"]],on="produit_id",how="left")

In [40]:
res2 = res[["categorie","est_annulee"]].groupby("categorie").agg(nb_annulees=("est_annulee","sum"),nb_commandes=("est_annulee","count"))

In [41]:
res3 = res2["nb_annulees"]/res2["nb_commandes"]*100

In [42]:
res3.sort_values(ascending=False) # Réseau a le taux le plus élevé

categorie
Réseau          10.968295
Accessoires     10.295728
Audio            9.923664
Téléphonie       9.918107
Stockage         9.130817
Informatique     8.803828
dtype: float64

In [154]:
data[0]["ca_perdu"].sum()

np.float64(407523.52)

---
# 🔵 PARTIE LOAD

### Ex L1 ⭐ — Export CSV
1. Exportez le DataFrame enrichi en CSV dans `../output/commandes_enrichies.csv`
2. Vérifiez la taille du fichier en Ko
3. Rechargez le CSV et vérifiez que le shape est identique

In [161]:
data[0].to_csv("output/commandes_enrichies.csv", index=False)

In [158]:
data[0].shape

(6149, 21)

In [181]:
cmd_enrichies = pd.read_csv("output/commandes_enrichies.csv",parse_dates=["date_commande"])

In [163]:
cmd_enrichies.shape

(6149, 21)

In [164]:
data[0].columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise', 'source', 'mois', 'annee', 'trimestre',
       'jour_semaine', 'tranche_montant', 'saison', 'est_annulee', 'ca_perdu',
       'delai_inscription_commande'],
      dtype='str')

In [165]:
cmd_enrichies.columns

Index(['commande_id', 'client_id', 'produit_id', 'quantite', 'prix_unitaire',
       'montant_total', 'date_commande', 'statut', 'mode_paiement',
       'region_livraison', 'devise', 'source', 'mois', 'annee', 'trimestre',
       'jour_semaine', 'tranche_montant', 'saison', 'est_annulee', 'ca_perdu',
       'delai_inscription_commande'],
      dtype='str')

In [166]:
data[0].dtypes

commande_id                               str
client_id                                 str
produit_id                                str
quantite                                int64
prix_unitaire                         float64
montant_total                         float64
date_commande                  datetime64[us]
statut                                    str
mode_paiement                             str
region_livraison                          str
devise                                    str
source                                    str
mois                                    int64
annee                                   int64
trimestre                               int64
jour_semaine                            int64
tranche_montant                      category
saison                               category
est_annulee                              bool
ca_perdu                              float64
delai_inscription_commande    timedelta64[us]
dtype: object

In [182]:
cmd_enrichies.dtypes

commande_id                              str
client_id                                str
produit_id                               str
quantite                               int64
prix_unitaire                        float64
montant_total                        float64
date_commande                 datetime64[us]
statut                                   str
mode_paiement                            str
region_livraison                         str
devise                                   str
source                                   str
mois                                   int64
annee                                  int64
trimestre                              int64
jour_semaine                           int64
tranche_montant                          str
saison                                   str
est_annulee                             bool
ca_perdu                             float64
delai_inscription_commande               str
dtype: object

### Ex L2 ⭐⭐ — Export Parquet
1. Exportez en Parquet dans `../output/commandes_S1.parquet`
2. Comparez la taille CSV vs Parquet
3. Rechargez le Parquet et vérifiez le shape
4. Mesurez le temps de lecture CSV vs Parquet avec `%%time`

In [57]:
data[0].to_parquet("output/commandes_enrichies.parquet", index=False)

In [58]:
cmd_enrichies = pd.read_parquet("output/commandes_enrichies.parquet")

In [59]:
cmd_enrichies.dtypes

commande_id                               str
client_id                                 str
produit_id                                str
quantite                                int64
prix_unitaire                         float64
montant_total                         float64
date_commande                  datetime64[us]
statut                                    str
mode_paiement                             str
region_livraison                          str
devise                                    str
source                                    str
mois                                    int64
annee                                   int64
trimestre                               int64
jour_semaine                            int64
tranche_montant                      category
saison                               category
est_annulee                              bool
ca_perdu                              float64
delai_inscription_commande    timedelta64[us]
dtype: object

In [60]:
cmd_enrichies.shape

(6149, 21)

### Ex L3 ⭐⭐ — SQLite
1. Créez une base SQLite `../output/ecommerce.db`
2. Chargez le DataFrame dans une table `commandes`
3. Créez une deuxième table `reporting` avec un agrégat par trimestre et région
4. Exécutez au moins 3 requêtes SQL directement depuis Python et affichez les résultats

In [43]:
from sqlalchemy import create_engine

In [44]:
engine = create_engine('sqlite:///output/ecommerce.db', echo=True)

In [45]:
sqlite_connection = engine.connect()

In [46]:
data[0].to_sql('commandes', con=engine, if_exists='replace', index=False)

2026-07-13 14:35:56,740 INFO sqlalchemy.engine.Engine BEGIN (implicit)

14:35:56 | BEGIN (implicit)

2026-07-13 14:35:56,746 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("commandes")

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_14596\4033020408.py:1: UserWarning: the 'timedelta' type is not supported, and will be written as integer values (ns frequency) to the database.
  data[0].to_sql('commandes', con=engine, if_exists='replace', index=False)
14:35:56 | PRAGMA main.table_info("commandes")

2026-07-13 14:35:56,748 INFO sqlalchemy.engine.Engine [raw sql] ()

14:35:56 | [raw sql] ()

2026-07-13 14:35:56,750 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("commandes")

14:35:56 | PRAGMA temp.table_info("commandes")

2026-07-13 14:35:56,752 INFO sqlalchemy.engine.Engine [raw sql] ()

14:35:56 | [raw sql] ()

2026-07-13 14:35:56,755 INFO sqlalchemy.engine.Engine
CREATE TABLE commandes (
	commande_id TEXT,
	client_id TEXT,
	produit_id TEXT,
	quantite BIGINT,
	prix_unitaire FLOAT,
	montant_total FLOAT,
	date_commande DATETIME,
	statut TEXT,
	mode_paiement TEXT,
	region_livraison TEXT,
	devise TEXT,
	source TEXT,
	mois BIGINT,
	annee BIGINT,
	trimestre BIGINT,
	jour_semaine BIGINT,
	tranche_montant TEXT,
	saison TEXT,
	est_annulee BOOLEAN,
	ca_perdu FLOAT,
	delai_inscription_commande BIGINT
)

14:35:56 |
CREATE TABLE commandes (
	commande_id TEXT,
	client_id TEXT,
	produit_id TEXT,
	quantite BIGINT,
	prix_unitaire FLOAT,
	montant_total FLOAT,
	date_commande DATETIME,
	statut TEXT,
	mode_paiement TEXT,
	region_livraison TEXT,
	devise TEXT,
	source TEXT,
	mois BIGINT,
	annee BIGINT,
	trimestre BIGINT,
	jour_semaine BIGINT,
	tranche_montant TEXT,
	saison TEXT,
	est_annulee BOOLEAN,
	ca_perdu FLOAT,
	delai_inscription_commande BIGINT
)

2026-07-13 14:35:56,756 INFO sqlalchemy.engine.Engine [no key 0.00131s] ()

14:35:56 | [no key 0.00131s] ()

2026-07-13 14:35:56,869 INFO sqlalchemy.engine.Engine INSERT INTO commandes (commande_id, client_id, produit_id, quantite, prix_unitaire, montant_total, date_commande, statut, mode_paiement, region_livraison, devise, source, mois, annee, trimestre, jour_semaine, tranche_montant, saison, est_annulee, ca_perdu, delai_inscription_commande) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

14:35:56 | INSERT INTO commandes (commande_id, client_id, produit_id, quantite, prix_unitaire, montant_total, date_commande, statut, mode_paiement, region_livraison, devise, source, mois, annee, trimestre, jour_semaine, tranche_montant, saison, est_annulee, ca_perdu, delai_inscription_commande) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)

2026-07-13 14:35:56,871 INFO sqlalchemy.engine.Engine [generated in 0.07653s] [('CMD-Q1-00001', 'CLI0496', 'PRD0081', 1, 49.36, 49.36, '2024-03-18 00:00:00.000000', 'annulée', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 3, 2024, 1, 0, '<100€', 'Hiver', 1, 49.36, 83462400000000), ('CMD-Q1-00002', 'CLI0305', 'PRD0058', 5, 118.62, 593.1, '2024-01-23 00:00:00.000000', 'livrée', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 1, 2024, 1, 1, '500-2000€', 'Hiver', 0, 0.0, 25747200000000), ('CMD-Q1-00003', 'CLI0044', 'PRD0128', 7, 99.94, 699.5799999999999, '2024-01-15 00:00:00.000000', 'livrée', 'PayPal', 'Nouvelle-Aquitaine', 'EUR', 'Q1_2024', 1, 2024, 1, 0, '500-2000€', 'Hiver', 0, 0.0, 110764800000000), ('CMD-Q1-00004', 'CLI0381', 'PRD0061', 8, 75.83, 606.64, '2024-01-17 00:00:00.000000', 'annulée', 'PayPal', 'PACA', 'EUR', 'Q1_2024', 1, 2024, 1, 2, '500-2000€', 'Hiver', 1, 606.64, 32400000000000), ('CMD-Q1-00005', 'CLI0187', 'PRD0040', 4, 71.91, 287.64, '2024-03-20 00:00:00.000000', 'en_cours', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 3, 2024, 1, 2, '100-500€', 'Hiver', 0, 0.0, 107395200000000), ('CMD-Q1-00006', 'CLI0450', 'PRD0045', 9, 55.24, 497.16, '2024-01-08 00:00:00.000000', 'livrée', 'CB', 'Auvergne-RA', 'EUR', 'Q1_2024', 1, 2024, 1, 0, '100-500€', 'Hiver', 0, 0.0, 16675200000000), ('CMD-Q1-00007', 'CLI0098', 'PRD0060', 7, 436.88, 3058.16, '2024-02-12 00:00:00.000000', 'annulée', 'Virement', 'Auvergne-RA', 'EUR', 'Q1_2024', 2, 2024, 1, 0, '>2000€', 'Hiver', 1, 3058.16, 68601600000000), ('CMD-Q1-00008', 'CLI0112', 'PRD0006', 9, 79.23, 713.07, '2024-03-03 00:00:00.000000', 'livrée', 'CB', 'Île-de-France', 'EUR', 'Q1_2024', 3, 2024, 1, 6, '500-2000€', 'Hiver', 0, 0.0, 66614400000000)  ... displaying 10 of 6149 total bound parameter sets ...  ('CMD-Q2-03199', 'CLI0187', 'PRD0091', 7, 75.28, 526.96, '2024-05-21 00:00:00.000000', 'livrée', 'CB', 'Nouvelle-Aquitaine', 'EUR', 'Q2_2024', 5, 2024, 2, 1, '500-2000€', 'Printemps', 0, 0.0, -9223372036854775808), ('CMD-Q2-03200', 'CLI0434', 'PRD0059', 8, 117.97, 943.76, '2024-06-25 00:00:00.000000', 'livrée', 'CB', 'PACA', 'EUR', 'Q2_2024', 6, 2024, 2, 1, '500-2000€', 'Printemps', 0, 0.0, -9223372036854775808)]

14:35:56 | [generated in 0.07653s] [('CMD-Q1-00001', 'CLI0496', 'PRD0081', 1, 49.36, 49.36, '2024-03-18 00:00:00.000000', 'annulée', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 3, 2024, 1, 0, '<100€', 'Hiver', 1, 49.36, 83462400000000), ('CMD-Q1-00002', 'CLI0305', 'PRD0058', 5, 118.62, 593.1, '2024-01-23 00:00:00.000000', 'livrée', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 1, 2024, 1, 1, '500-2000€', 'Hiver', 0, 0.0, 25747200000000), ('CMD-Q1-00003', 'CLI0044', 'PRD0128', 7, 99.94, 699.5799999999999, '2024-01-15 00:00:00.000000', 'livrée', 'PayPal', 'Nouvelle-Aquitaine', 'EUR', 'Q1_2024', 1, 2024, 1, 0, '500-2000€', 'Hiver', 0, 0.0, 110764800000000), ('CMD-Q1-00004', 'CLI0381', 'PRD0061', 8, 75.83, 606.64, '2024-01-17 00:00:00.000000', 'annulée', 'PayPal', 'PACA', 'EUR', 'Q1_2024', 1, 2024, 1, 2, '500-2000€', 'Hiver', 1, 606.64, 32400000000000), ('CMD-Q1-00005', 'CLI0187', 'PRD0040', 4, 71.91, 287.64, '2024-03-20 00:00:00.000000', 'en_cours', 'CB', 'Occitanie', 'EUR', 'Q1_2024', 3, 2024, 1, 2, '100-500€', 'Hiver', 0, 0.0, 107395200000000), ('CMD-Q1-00006', 'CLI0450', 'PRD0045', 9, 55.24, 497.16, '2024-01-08 00:00:00.000000', 'livrée', 'CB', 'Auvergne-RA', 'EUR', 'Q1_2024', 1, 2024, 1, 0, '100-500€', 'Hiver', 0, 0.0, 16675200000000), ('CMD-Q1-00007', 'CLI0098', 'PRD0060', 7, 436.88, 3058.16, '2024-02-12 00:00:00.000000', 'annulée', 'Virement', 'Auvergne-RA', 'EUR', 'Q1_2024', 2, 2024, 1, 0, '>2000€', 'Hiver', 1, 3058.16, 68601600000000), ('CMD-Q1-00008', 'CLI0112', 'PRD0006', 9, 79.23, 713.07, '2024-03-03 00:00:00.000000', 'livrée', 'CB', 'Île-de-France', 'EUR', 'Q1_2024', 3, 2024, 1, 6, '500-2000€', 'Hiver', 0, 0.0, 66614400000000)  ... displaying 10 of 6149 total bound parameter sets ...  ('CMD-Q2-03199', 'CLI0187', 'PRD0091', 7, 75.28, 526.96, '2024-05-21 00:00:00.000000', 'livrée', 'CB', 'Nouvelle-Aquitaine', 'EUR', 'Q2_2024', 5, 2024, 2, 1, '500-2000€', 'Printemps', 0, 0.0, -9223372036854775808), ('CMD-Q2-03200', 'CLI0434', 'PRD0059', 8, 117.97, 943.76, '2024-06-25 00:00:00.000000', 'livrée', 'CB', 'PACA', 'EUR', 'Q2_2024', 6, 2024, 2, 1, '500-2000€', 'Printemps', 0, 0.0, -9223372036854775808)]

2026-07-13 14:35:56,891 INFO sqlalchemy.engine.Engine COMMIT

14:35:56 | COMMIT

6149

In [48]:
res = data[0][["trimestre","region_livraison","montant_total","ca_perdu"]].groupby(["trimestre","region_livraison"]).agg({
'montant_total': 'sum',
'ca_perdu': 'sum'
})

In [49]:
res

                              montant_total  ca_perdu
trimestre region_livraison
1         Auvergne-RA             369358.30  33166.54
          Nouvelle-Aquitaine      385457.30  32309.27
          Occitanie               397402.76  54844.43
          PACA                    381199.40  35183.32
          Île-de-France           406540.08  48049.89
2         Auvergne-RA             410398.27  41419.41
          Nouvelle-Aquitaine      389914.59  56538.35
          Occitanie               455210.47  35953.72
          PACA                    400641.67  26094.34
          Île-de-France           441011.94  43964.25

In [52]:
res.to_sql('reporting', con=engine, if_exists='replace')

2026-07-13 15:11:14,044 INFO sqlalchemy.engine.Engine BEGIN (implicit)

15:11:14 | BEGIN (implicit)

2026-07-13 15:11:14,047 INFO sqlalchemy.engine.Engine PRAGMA main.table_info("reporting")

15:11:14 | PRAGMA main.table_info("reporting")

2026-07-13 15:11:14,049 INFO sqlalchemy.engine.Engine [raw sql] ()

15:11:14 | [raw sql] ()

2026-07-13 15:11:14,052 INFO sqlalchemy.engine.Engine PRAGMA temp.table_info("reporting")

15:11:14 | PRAGMA temp.table_info("reporting")

2026-07-13 15:11:14,053 INFO sqlalchemy.engine.Engine [raw sql] ()

15:11:14 | [raw sql] ()

2026-07-13 15:11:14,056 INFO sqlalchemy.engine.Engine
CREATE TABLE reporting (
	trimestre BIGINT,
	region_livraison TEXT,
	montant_total FLOAT,
	ca_perdu FLOAT
)

15:11:14 |
CREATE TABLE reporting (
	trimestre BIGINT,
	region_livraison TEXT,
	montant_total FLOAT,
	ca_perdu FLOAT
)

2026-07-13 15:11:14,058 INFO sqlalchemy.engine.Engine [no key 0.00143s] ()

15:11:14 | [no key 0.00143s] ()

2026-07-13 15:11:14,104 INFO sqlalchemy.engine.Engine CREATE INDEX ix_reporting_region_livraison ON reporting (region_livraison)

15:11:14 | CREATE INDEX ix_reporting_region_livraison ON reporting (region_livraison)

2026-07-13 15:11:14,112 INFO sqlalchemy.engine.Engine [no key 0.00791s] ()

15:11:14 | [no key 0.00791s] ()

2026-07-13 15:11:14,134 INFO sqlalchemy.engine.Engine CREATE INDEX ix_reporting_trimestre ON reporting (trimestre)

15:11:14 | CREATE INDEX ix_reporting_trimestre ON reporting (trimestre)

2026-07-13 15:11:14,145 INFO sqlalchemy.engine.Engine [no key 0.01130s] ()

15:11:14 | [no key 0.01130s] ()

2026-07-13 15:11:14,171 INFO sqlalchemy.engine.Engine INSERT INTO reporting (trimestre, region_livraison, montant_total, ca_perdu) VALUES (?, ?, ?, ?)

15:11:14 | INSERT INTO reporting (trimestre, region_livraison, montant_total, ca_perdu) VALUES (?, ?, ?, ?)

2026-07-13 15:11:14,183 INFO sqlalchemy.engine.Engine [generated in 0.01189s] [(1, 'Auvergne-RA', 369358.3, 33166.54), (1, 'Nouvelle-Aquitaine', 385457.3, 32309.27), (1, 'Occitanie', 397402.76, 54844.43), (1, 'PACA', 381199.4, 35183.32), (1, 'Île-de-France', 406540.08, 48049.89), (2, 'Auvergne-RA', 410398.27, 41419.41), (2, 'Nouvelle-Aquitaine', 389914.59, 56538.35), (2, 'Occitanie', 455210.47000000003, 35953.72), (2, 'PACA', 400641.67, 26094.34), (2, 'Île-de-France', 441011.94, 43964.25)]

15:11:14 | [generated in 0.01189s] [(1, 'Auvergne-RA', 369358.3, 33166.54), (1, 'Nouvelle-Aquitaine', 385457.3, 32309.27), (1, 'Occitanie', 397402.76, 54844.43), (1, 'PACA', 381199.4, 35183.32), (1, 'Île-de-France', 406540.08, 48049.89), (2, 'Auvergne-RA', 410398.27, 41419.41), (2, 'Nouvelle-Aquitaine', 389914.59, 56538.35), (2, 'Occitanie', 455210.47000000003, 35953.72), (2, 'PACA', 400641.67, 26094.34), (2, 'Île-de-France', 441011.94, 43964.25)]

2026-07-13 15:11:14,188 INFO sqlalchemy.engine.Engine COMMIT

15:11:14 | COMMIT

10

In [53]:
sql_query = "SELECT COUNT(*) FROM reporting"
r = pd.read_sql_query(sql_query, engine)

2026-07-13 15:49:06,515 INFO sqlalchemy.engine.Engine BEGIN (implicit)

15:49:06 | BEGIN (implicit)

2026-07-13 15:49:06,516 INFO sqlalchemy.engine.Engine SELECT COUNT(*) FROM reporting

15:49:06 | SELECT COUNT(*) FROM reporting

2026-07-13 15:49:06,518 INFO sqlalchemy.engine.Engine [raw sql] ()

15:49:06 | [raw sql] ()

2026-07-13 15:49:06,521 INFO sqlalchemy.engine.Engine ROLLBACK

15:49:06 | ROLLBACK

In [54]:
r

   COUNT(*)
0        10

In [55]:
sql_query = "SELECT region_livraison, SUM(montant_total) FROM reporting GROUP BY region_livraison"
r = pd.read_sql_query(sql_query, engine)
r

2026-07-13 15:50:45,013 INFO sqlalchemy.engine.Engine BEGIN (implicit)

15:50:45 | BEGIN (implicit)

2026-07-13 15:50:45,014 INFO sqlalchemy.engine.Engine SELECT region_livraison, SUM(montant_total) FROM reporting GROUP BY region_livraison

15:50:45 | SELECT region_livraison, SUM(montant_total) FROM reporting GROUP BY region_livraison

2026-07-13 15:50:45,015 INFO sqlalchemy.engine.Engine [raw sql] ()

15:50:45 | [raw sql] ()

2026-07-13 15:50:45,018 INFO sqlalchemy.engine.Engine ROLLBACK

15:50:45 | ROLLBACK

     region_livraison  SUM(montant_total)
0         Auvergne-RA           779756.57
1  Nouvelle-Aquitaine           775371.89
2           Occitanie           852613.23
3                PACA           781841.07
4       Île-de-France           847552.02

In [56]:
sql_query = "SELECT COUNT(DISTINCT client_id) FROM commandes"
r = pd.read_sql_query(sql_query, engine)
r

2026-07-13 15:52:29,715 INFO sqlalchemy.engine.Engine BEGIN (implicit)

15:52:29 | BEGIN (implicit)

2026-07-13 15:52:29,716 INFO sqlalchemy.engine.Engine SELECT COUNT(DISTINCT client_id) FROM commandes

15:52:29 | SELECT COUNT(DISTINCT client_id) FROM commandes

2026-07-13 15:52:29,718 INFO sqlalchemy.engine.Engine [raw sql] ()

15:52:29 | [raw sql] ()

2026-07-13 15:52:29,723 INFO sqlalchemy.engine.Engine ROLLBACK

15:52:29 | ROLLBACK

   COUNT(DISTINCT client_id)
0                        543

In [64]:
import hashlib

In [61]:
df_json = data[0].to_json()

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_14596\2454876444.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df_json = data[0].to_json()

In [65]:
hash_object = hashlib.sha256(df_json.encode())
hash_code = hash_object.hexdigest()
hash_code

'46cf3653e8a8b939b8316c925b21565091ea11ef9463bee805c21edb84b14a05'

In [66]:
df2_json = cmd_enrichies.to_json()

C:\Users\Utilisateur\AppData\Local\Temp\ipykernel_14596\238308841.py:1: Pandas4Warning: The default 'epoch' date format is deprecated and will be removed in a future version, please use 'iso' date format instead.
  df2_json = cmd_enrichies.to_json()

In [67]:
hash_object = hashlib.sha256(df2_json.encode())
hash_code = hash_object.hexdigest()
hash_code

'a9b911f8d0f2244567ff529e77917b9a632ced2984aa815f76f492f657c488de'

In [72]:
row_hashes = pd.util.hash_pandas_object(data[0], index=False).values.tobytes()
hash_code = hashlib.sha256(row_hashes).hexdigest()
hash_code

'cbf2b85b024d30f06fe7e3de47622e4fe44f437d28adb4a30f29539a3e4ca080'

In [73]:
row_hashes = pd.util.hash_pandas_object(cmd_enrichies, index=False).values.tobytes()
hash_code = hashlib.sha256(row_hashes).hexdigest()
hash_code

'cbf2b85b024d30f06fe7e3de47622e4fe44f437d28adb4a30f29539a3e4ca080'

In [74]:
row_hashes = pd.util.hash_pandas_object(data[1], index=False).values.tobytes()
hash_code = hashlib.sha256(row_hashes).hexdigest()
hash_code

'9ca1e5fc7c34866f62bd97c52cee6efcd00996d5ea186b8c19e1747523139d97'

### Ex L4 ⭐⭐⭐ — Parquet partitionné
Exportez le DataFrame en Parquet partitionné par `trimestre` et `region_livraison`.

Puis répondez :
- Combien de fichiers Parquet sont créés ?
- Quelle est la taille totale vs le Parquet non partitionné ?
- Quel est l'avantage du partitionnement pour PySpark ?

In [ ]:
# TON CODE ICI

---
# 🔴 PIPELINE COMPLET

### Ex P1 ⭐⭐ — Pipeline modulaire
Écris 3 fonctions séparées :
- `extract(data_dir) -> dict`
- `transform(sources: dict) -> pd.DataFrame`
- `load(df, output_dir) -> None`

Chacune doit avoir une docstring et des logs.
Teste chaque fonction indépendamment.

In [ ]:
# TON CODE ICI

### Ex P2 ⭐⭐⭐ — Pipeline avec gestion d'erreurs
Améliore ton pipeline avec :
1. `try/except` sur chaque étape critique
2. Un log d'erreur détaillé si une étape échoue
3. La pipeline ne doit pas crasher complètement si un fichier est manquant — elle doit logger l'erreur et continuer avec les autres

In [ ]:
# TON CODE ICI

### Ex P3 ⭐⭐⭐ — Tests unitaires du pipeline
Écris 5 tests pour ton pipeline :
1. `test_extract_retourne_4_sources()`
2. `test_transform_supprime_doublons()`
3. `test_transform_pas_de_prix_negatif()`
4. `test_transform_montant_coherent()`
5. `test_load_cree_les_fichiers()`

Chaque test affiche ✅ PASS ou ❌ FAIL.

In [ ]:
# TON CODE ICI

### Ex P4 ⭐⭐⭐⭐ — PROJET FINAL : Pipeline automatisé
Crée un pipeline complet qui :

1. **Détecte automatiquement** tous les fichiers CSV dans `../data_etl/` qui commencent par `commandes_`
2. **Les traite tous** sans avoir à spécifier les chemins manuellement
3. **Génère un rapport HTML** avec :
   - Les statistiques clés (CA, nb commandes, taux annulation)
   - 3 graphiques Plotly intégrés
4. **Sauvegarde** en CSV + Parquet + SQLite
5. **Loggue** chaque étape avec timestamps

C'est exactement ce que vous ferez en PySpark la semaine prochaine, mais à l'échelle de plusieurs To.

📎 Docs utiles :
- [glob — trouver des fichiers](https://docs.python.org/3/library/glob.html)
- [logging](https://docs.python.org/3/library/logging.html)
- [Plotly — export HTML](https://plotly.com/python/interactive-html-export/)

In [ ]:
# TON CODE ICI